# Generated by Django 5.2.14 on 2026-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='on',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='shipment',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='eta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
