# Generated by Django 5.2.14 on 2026-05-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_shipment_on_shipment_progress_alter_shipment_eta'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='distance_km',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_temp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_weather',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='risk',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Low', max_length=50),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Delayed', 'Delayed'), ('At Risk', 'At Risk'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
