# Generated by Django 5.2.14 on 2026-05-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_shipment_destination_temp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='current_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='dest_lng',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_lng',
            field=models.FloatField(default=0.0),
        ),
    ]
