# Generated by Django 5.2.14 on 2026-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_shipment_current_lat_shipment_current_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('At Risk', 'At Risk'), ('Delayed', 'Delayed'), ('Delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
