# Generated by Django 5.2.14 on 2026-05-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alert',
            name='ai_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='shipment_id_ref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='alert',
            name='level',
            field=models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=50),
        ),
    ]
